### ISSUE TITLE
Add demosaic.py to pipeline to convert stereo images to image files

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#112]

**Comment by max-zilla** [comment]
Plan to deploy this extractor this week.

**Comment by max-zilla** [comment]
I have a VM with this extractor installed and dependencies updated, I think ready to run.

Outstanding question is whether we should support writing resulting JPG to /derived_data directory accessible via Globus, or deploy now and handle that later.

**Comment by max-zilla** [comment]
@robkooper before starting up the extractors, we need to mount the Roger /sites directory to the VMs they are going to run on. Then we can write extractor outputs to the /sites/ua-mac/derived_data/Level1/<extractor> directory.

**Comment by robkooper** [comment]
You will need to send the IP address of the VM to JD, then I'll show how to mount the drive.

**Comment by max-zilla** [comment]
@jdmaloney the VM for the demosaic extractor I created has floating IP 141.142.170.137. Can you do whatever is required to allow mounting of roger to it?

I think in general we want to mount **READ ONLY**
```
/projects/arpae/terraref/sites/ua-mac/raw_data
```
Don't want to limit it to a particular sensor in this case because it triggers from several sensors.

Then mount for **WRITE** it should be tailored to the specific extractor that VM.
```
/projects/arpae/terraref/sites/ua-mac/Level_1/demosaic
```
Under /demosaic the extractor can replicate the directory structure of the source dataset, probably from the <sensor name> level down.

**Comment by jdmaloney** [comment]
@max-zilla I've created those exports (and the Level 1 demosaic directory).  Make sure the user doing the writing on the VM has the id: 47852 so it can have permission to write.  Let me know if that would be a problem and we can work it a different way, but having that specific uid for that user is preferred if possible.

**Comment by max-zilla** [comment]
Extractor is now in this repo: https://github.com/terraref/extractors-stereo-rgb 

I updated it to leverage the local-mount ROGER code.

**Comment by max-zilla** [comment]
This has been deployed. Results accumulating in /ua-mac/Level_1/demosaic.
