### ISSUE TITLE
Verify correctness of Logger data before committing changes

### ISSUE THREAD

**Issue by czender** [terraref/computing-pipeline#116]
When new capabilities or formatting changes are made to EnvironmentalLogger data files, the changes should be checked for correctness before committing them to a production workflow. Correctness means, at least, verifying properly formatted JSON. Otherwise the downstream workflow might break. Presumably someone at Lemnatec, like @TinoDornbusch, could run such a test.

### Description
There are a few JSON validators available. @FlyingWithJerome and @dlebauer know more details. 
For example, according to Jerome, there are unexpected JSON formatting issues with 
EnvironmentLogger/2016-06-01/2016-06-01_10-52-52_environmentlogger.json

**Comment by dlebauer** [comment]
@FlyingWithJerome could you please provide an example of the error messages you get and the file that causes it (or dates that contain the problem)?

**Comment by TinoDornbusch** [comment]
@czender @dlebauer I am not sure whether this is related to some software upgrade attempts. There were some requests from Solmaz to include e.g. Scanning speed in hyperspec json.

The problem is that MArkus Radermacher, the only one to fix this, is in holiday for two weeks. We have had discussions in our team that changes in the software do not make much sense during an ongoing experiment. Just causes trouble, both on image acquisition and data processing.

I will do my best to fix what I can with my limited capabilities.

**Comment by FlyingWithJerome** [comment]
@dlebauer Yes, I have two error messages here. Both of them are from Professor Zender.
The first one is on the JSONs from 04-17, and it is raised by built-in JSON parser:

zender@cg-gpu01:~/nco$ python ${HOME}/terraref/computing-pipeline/scripts/hyperspectral/EnvironmentalLoggerAnalyser.py /projects/arpae/terraref/raw_data/ua-mac/EnvironmentLogger/2016-04-07/2016-04-07_12-00-07_enviromentlogger.json ~/rgr
(0.57725892345086449, 1.1872645869922727)
Processing /projects/arpae/terraref/raw_data/ua-mac/EnvironmentLogger/2016-04-07/2016-04-07_12-00-07_enviromentlogger.json....
Traceback (most recent call last):
  File "/home/zender/terraref/computing-pipeline/scripts/hyperspectral/EnvironmentalLoggerAnalyser.py", line 278, in <module>
    tempJSONMasterList, wavelength, spectrum, downwellingSpectralFlux = JSONHandler(fileInputLocation)
  File "/home/zender/terraref/computing-pipeline/scripts/hyperspectral/EnvironmentalLoggerAnalyser.py", line 127, in JSONHandler
    return json.loads(fileHandler.read()), wavelength, spectrum, downwellingSpectralFlux
  File "/sw/python-2.7.10/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/sw/python-2.7.10/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 4151 column 2 - line 161851 column 2 (char 101546 - 3960234)

--------------------------------------------------------------------------------------------------------------------------------
The second one is from a newer JSON, on 06-01. This is not really caused by the JSONs. I downloaded the JSONs from this day and saw that the JSONs had a new format, so I will make changes on EnvironmentalLoggerAnalyser to fit the newest format.

zender@cg-gpu01:~/nco$ python ${HOME}/terraref/computing-pipeline/scripts/hyperspectral/EnvironmentalLoggerAnalyser.py /projects/arpae/terraref/raw_data/ua-mac/EnvironmentLogger/2016-06-01/2016-06-01_10-52-52_environmentlogger.json ~/rgr
(0.57725892345086449, 1.1872645869922727)
Processing /projects/arpae/terraref/raw_data/ua-mac/EnvironmentLogger/2016-06-01/2016-06-01_10-52-52_environmentlogger.json....
Traceback (most recent call last):
  File "/home/zender/terraref/computing-pipeline/scripts/hyperspectral/EnvironmentalLoggerAnalyser.py", line 278, in <module>
    tempJSONMasterList, wavelength, spectrum, downwellingSpectralFlux = JSONHandler(fileInputLocation)
  File "/home/zender/terraref/computing-pipeline/scripts/hyperspectral/EnvironmentalLoggerAnalyser.py", line 125, in JSONHandler
    fileLocation)
  File "/home/zender/terraref/computing-pipeline/scripts/hyperspectral/EnvironmentalLoggerAnalyser.py", line 106, in wavelengthSpectrumAnddownwellingSpectralFlux
    wvl_lgr.append(float(tempList[i][tempList[i].find(':') + 1: -2]) * 1e-9)
ValueError: could not convert string to float:

**Comment by dlebauer** [comment]
@FlyingWithJerome what is the difference in the format? from 06-01? 

In general, we can deal with re-processing older formats (e.g. from 04-17). I think these changes were dealt with in terraref/reference-data#26, but we will deal with re-processing those at the end of the first growing season when we re-process the entire season of data with a common version (alpha release Nov 2016) of all extractors.

**Comment by dlebauer** [comment]
@TinoDornbusch, @LTBen, @markus-radermacher-lemnatec I think two points are: 

1) do not change existing structure of meta-data on an ad-hoc basis. 
2) If additional information is required, adding fields should not break code, as long as the existing format is valid and the fields are not changed. 
3) Requests such as those from @solmazhajmohammadi should be made as a github issue so that people who are writing code that depends on the metadata file have a chance to review the new proposed format before it is implemented.
4) at a minimum, new formats should be tested for validity. Perhaps we need something like a json validator file that defines the structure and that jsonlint can compare to.

**Comment by czender** [comment]
My apologies for the misunderstanding. The current problem is due a change in the JSON file. The file itself is JSON compliant. Something was either added or changed that broke our python translator to netCDF. Best method to avoid this in the future is to run 
`python EnvironmentalLoggerAnalyser.py  logger_input.json output_directory `
and if that does not succeed, notify us and send us the logger_input.json file. Again, apologies for thinking this was a bad JSON  issue. It's not. Miscommunication between me and Jerome.

**Comment by SolmazHajmohammadi-LemnaTec** [comment]
@dlebauer  Sure, I'll keep on my mind to open a new issue for the next time.
Regarding the issue that Tino mentioned: Right now the recorded speed for hyperspectral data shows the initial speed when measurement got started which is zero in some cases or small number which is the corrective movement of the gantry. The difference will be reporting the target speed instead of the initial speed and I think there wont be any change in the JSON file format.
I can open a new issue for this, if you think it is necessary.
