### ISSUE TITLE
Hyperspectral pipeline output is 4x as large as input 

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#139]
This was initially observed by @yanliu-chn; @czender suggested that it may be related to netcdf-4

**Comment by czender** [comment]
Just checked and the figure is really output = 3.001 x input. This is primarily due to the addition of the output field rfl_img (image reflectance), which is stored as four byte floats. Therefore this field alone is twice the size of the input image, which is also stored in the file. Those two fields alons gets us to output =3x input. The small residual is due to other diagnostic fields that were added. To note: the script has a lossless compression switch (-c) which is off by default to enhance speed during testing. So the output fileseize is well understood, and can be reduced simply by activating the built-in compression, which reduces sizes to output = 1.98 x input. Sizes could be further reduced by applying lossy compression, or eliminating some fields currently archived. So I am closing this issue.
