### ISSUE TITLE
KSU UAV data pipeline planning

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#162]
This is a followup from call on 9/6/2016 including:
- Mark Lucas, KSU, UAV data preprocessing + db storage and archiving
- Geoff Morris, KSU, sorghum geneticist
- Jesse Poland, KSU, more focused on wheat
- Kevin Wang, KSU, ag engineer & data processing, e.g. NDVI + height from images
- @pless, WashU
- @smarshall-bmr, MAC scanner operator
- myself and @jdmaloney, NCSA

...focused around setting up a pipeline between KSU and UI. Currently the data flow at KSU is as follows:
1. captured data is uploaded to a central server
2. data is processed to generate database entries + do file renaming
3. images are georeferenced
4. raw data is archived into folder structure
5. two primary DB tables store a) metadata about the images and b) UAV flight data including number of images, coverage, time, etc.

After discussion, current plan is generally:
- I will modify the monitor service used at MAC and soon to be used at Danforth to support SQL query as a way to fetch list of files to transfer
- Mark and I will coordinate to determine SQL queries necessary to:
  - get new list of images that have not yet been sent to NCSA
  - get metadata associated with those images 
- my monitor service will periodically query the DB for new files + metadata and transfer to NCSA

Other topics that arose include:
- is there consideration of other data in the future for TERRA, e.g. wheat?
- what is the 'hello world' extractor for UAV data?
- @pless will be in Illinois in early October
- does KSU have a Globus setup already? @jdmaloney thought the beocat Globus endpoint might be enough. What user will we use?

**Comment by max-zilla** [comment]
Regarding the SQL queries:
I plan to modify my code to use a Python SQL library like: http://www.tutorialspoint.com/python/python_database_access.htm …then I would imagine the logic can be:
- Execute GetFileList SQL query to get a database cursor on a set of result rows – this should return a list of files and if possible their timestamps
- Iterate across files and execute GetFileMetadata on each one (?) to fetch that file’s metadata
- Bundle current file + metadata into a JSON file and queue for sending
- Repeat for next file until we reach them all, and record the latest file we sent
- Rerun GetFileList every x minutes, with query only returning files newer than the latest file from last time

So on KSU end the GetFileList and GetFileMetadata queries are the critical pieces. Pseudo:
- GetFileList = select all filename, timestamp from files_table where timestamp > LAST_SEEN_TIMESTAMP
- GetFileMetadata = select all ??? from file_info where filename = CURRENT_FILE

**Comment by marklucascork** [comment]
Thanks Max. I will work on getting example queries to you over the next few days.

There are two tables for the UAS image data sets:
uas_run: which stores information about each flight.
uas_images: which stores information about all of the image files associated with each flight.

For the GetFileList query, there is no timestamp indicating when the file was created stored in the uas_run table itself. However, there is a record ID which is an auto-incremented running number assigned to each row which could be used instead: i.e. instead of LAST_SEEN_TIMESTAMP we could used LAST_SEEN_RECORD_ID.

Regarding the GetFileMetadata query, there is an  flight_id stored in the uas_run table that is also stored for each metadata record in the uas_images table. This identifies all metadata records stored for each flight. So the query would for GetFileMetadata for a specific flight  would be to select all rows from uas_images where uas_images.run_id=uas_run.flight_id.

The image file sets are stored as tar files in a dedicated folder on our server.

**Comment by marklucascork** [comment]
One question regarding the use of Globus Connect: I got myself set up to use Globus Connect yesterday, and I have tested transferring files between my computer and the Beocat server. In order to do this, I was told that I had to have an account on Beocat. 

Does this mean that anyone who wants to retrieve files from Beocat also has to have an account on Beocat? Or is it sufficient to share the folder containing the UAS files with a specific GLOBUS username?

**Comment by max-zilla** [comment]
@jdmaloney can you weigh in on Globus question above?

@marklucascork feedback re: SQL looks good - incrementing field is easier than a timestamp, and we should be able to build a JSON object from a set of metadata rows pretty readily.

**Comment by jdmaloney** [comment]
@marklucascork Short answer is it depends.  

It is possible to set up a Globus Share on an existing endpoint that does not require users to have valid auth on the underlying system.  This is what we do with the terraref endpoint that we host here at NCSA.  We can add individual Globus ID's to have read-only or read/write permissions on the directory being shared and they never have to have any NCSA credentials.  

I don't believe this sharing feature is a free feature in Globus, but if KSU is paying Globus it may have access to this ability.  So I think the best thing may be to ask the admins on the system.  If they tell you they can create a shared endpoint, then that would work great and we'll get you a Globus ID to give permissions to.  

Hope that helps, but please feel free to let me know if that doesn't clear something up, or if more questions arise.

**Comment by marklucascork** [comment]
Thanks @jdmaloney. I have aske our administrators about whether our Globus Connect endpoit supports sharing with valid Globus User ID.

**Comment by marklucascork** [comment]
Here are example SQL queries required for retrieving our UAS data:
A: **GetFileList query**

SELECT record_id,flight_id FROM uas_run WHERE record_id > 0;

The above example retrieves information about all entries in the uas_run table. If you wish to retrieve entries newer than the last one retrieved, replace 0 with the record_id of the last data set retrieved:

SELECT record_id,flight_id FROM uas_run WHERE record_id > LAST_SEEN_RECORD_ID;

B: **GetFileMetadata**

SELECT * FROM uas_images WHERE flight_id = 'uas_20160107_065204_20160107_065728’;

The above example will retrieve all metadata records for the flight_id uas_20160107_065204_20160107_065728. In order to get data for any other flight, simply use the flight_id(s) retrieved from the GetFileList query above.

The image files themselves are stored on Beocat in the folder /bulk/jpoland/images/uas. Each tar file contains the image files and any raw data associated with the flight e.g. log files.

I am hoping that we can use the Globus Share facility to share these with you. If not, you will need to set up an account on Beocat. I will send instructions on how to do this if this turns our to be necessary.

Please let me know if you have any questions.

**Comment by max-zilla** [comment]
@marklucascork this looks great. I'll work on getting SQL query support implemented in the pipeline monitor next week.

**Comment by marklucascork** [comment]
I tried sharing the uas folder on Beocat and found that sharing is not enabled at KSU. I verified this with the Beocat system administrators.

I believe that this means that you will need to get an account on Beocat in order to access the files that you need. I may also need to give you a read-only account on the database. However, we could probably work around this by invoking a script that queries the database using e.g. my credentials.

Instructions for getting a Beocat account:

1. The first thing that you need to do to get access is to apply for an EID. The link to the application page is http://eid.ksu.edu
2. Once you receive your EID, then you need to apply for an account on Beocat (the KSU cluster). The application page for Beocat is https://account.beocat.ksu.edu/user

Let me know when you have established your account on Beocat and we will take it from there.

**Comment by craig-willis** [comment]
This is a stale issue with no comments in last 2 months. Please create new issues if work remains or put this content in the documentation.
