### ISSUE TITLE
Identify method(s) of archiving and publishing data with DOI

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#19]
How can NDS incorporate what exists, and what else might be needed.

Agenda: 

1. What does Clowder already have and what other features will it need?
2. What methods of archiving / identifying are appropriate for different data sub-sets and releases?
3. How to indicate conditions of reuse, credit, etc.?

Notes: 

* assigning identifiers for each pieces for within the system (done by Clowder)
* DOIs for use in research referencing, as few as 1x/y unless otherwise needed.
* Talk to @robkooper regarding SEAD project implementations / needs. what can be taken
* How to make sure that data creators get credit - sufficient credit that they are comfortable with our mandate to release data early / often. Perhaps providing a citable 'data descriptor' such as a Nature Scientific Data ([about](http://www.nature.com/sdata/about/principles/); [instructions for authors](http://www.nature.com/sdata/for-authors)) article?
* samples of the first datasets [are on Box](https://uofi.box.com/s/c9ngkwi3xvtfr0ei5zfzgf4jya0dmrlc) and [also on Clowder](http://141.142.209.122/clowder/)

**Comment by rachelshekar** [comment]
How do researchers cite the data they use?
Acknowledgement clause

**Comment by dlebauer** [comment]
@rachelshekar next step would be to have a meeting with Heidi Imker, Sarah Williams, and (Rob or Kenton) in which we discuss options about where in the pipeline to 'publish' data and how to do so. The biggest challenge will be ensuring to trace the provenance of contributed data sets, so that we can make it easy for researchers to publish their own data and accurately cite the data that they use, as well as the provenance of derived data products.

**Comment by rachelshekar** [comment]
pending

  http://doodle.com/poll/f567s9q9fr7k7wut

**Comment by rachelshekar** [comment]
https://docs.google.com/document/d/1UtbhumdL9VPGaoVlkos_s2WkUvosZTBwJr2ea1UMCuk/edit
