### ISSUE TITLE
Tractor data: GPS positions do not match for NDVI and temperature 

### ISSUE THREAD

**Issue by Mamatemenrs** [terraref/computing-pipeline#192]
### Description

There are some differences between the number of GPS points measured for thermal, sonar and NDVI data. Basically, on all sampling dates, the number GPS points for NDVI are fewer (140 - 180 samples) than for the other types of data. 

Can any one comment on that.

**Comment by dlebauer** [comment]
@Mamatemenrs I've assigned this to @Andrade-Pedro. I believe @anfrench and @kthorp also run the tractor. For reference, here is a paper that describes the tractor 
[(Sanchez et al 2014)](https://github.com/terraref/computing-pipeline/files/556186/sanchez2014def.pdf)

**Comment by dlebauer** [comment]
@Mamatemenrs is there an open issue specifying tasks related to the tractor data?

**Comment by dlebauer** [comment]
@Mamatemenrs See also #150 because the workflows are similar for these platforms
![image](https://cloud.githubusercontent.com/assets/464871/19782328/fa658d22-9c52-11e6-8551-d5dc324f2d7c.png)

**Comment by jtheun** [comment]
Yes sir. There are less points for NDVI due to 'skips' in the serial output of the RT200 controller. The green seeker sensors are on a can bus network with the RT200 unit. The output message from the RT200 on the serial port was configured to output at 5Hz. Every once and awhile, there is a blank message (contains only the new line and carriage return characters). It appears to be random and no adjustments or a change in settings make a difference.
