### ISSUE TITLE
Reduce mem requirements of hyperspectral extractor

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#194]
@robkooper @yanliu-chn @jterstriep @czender 

Jeff might be able to write a preprocessing script to slice the _raw file into smaller chunks for processing instead of loading the entire 62 GB file at once, but in general we should figure out some way to reduce memory requirements of the hyperspectral extractor. The mem requirements are pushing up against upper limit of RAM on Roger nodes we have available.

Making this issue as a place for us to discuss.

**Comment by yanliu-chn** [comment]
@jterstriep here is the HPC launcher script for plantcv extractor, for your reference: https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/extractors-plantcv/browse

**Comment by czender** [comment]
The HS workflow completed processing a 62GB raw file in the batch queue. I had thought it was hanging because it did not finish in < 1 hr. I resubmitted with a 3 hour limit and it finished in 94 minutes. Setting the batch time to 2 hours will should be sufficient. I think the peak usage was ~232 GB RAM. Hence I would expect similar results for RAM demands < ~250 GB (raw files < ~67 GB). Whether it will work when RAM demands exceed 256 GB is untested. RAM usage is ~4xsizeof(raw) and output file is ~3xsizeof(raw).

**Comment by rachelshekar** [comment]
@jterstriep  - can this issue be closed?

**Comment by rachelshekar** [comment]
@jterstriep ???

**Comment by rachelshekar** [comment]
This is not a problem - Jeff

**Comment by dlebauer** [comment]
per discussion today ... Roger can currently handle the largest files; takes approx. 1.5 hr to process

**Comment by czender** [comment]
If the project has extra money to spend, consider adding some big memory (e.g., 1 TB or greater) nodes to Roger (or another cluster). Then if working with 128 GB plant reflectance field becomes troublesome, a potential hardware workaround (fatter nodes) will be available.
