### ISSUE TITLE
Wavelength Number for VNIR and SWIR

### ISSUE THREAD

**Issue by FlyingWithJerome** [terraref/computing-pipeline#205]
@solmazhajmohammadi 
@czender and I noticed that the wavelength number in SWIR from November 2 is pretty strange. It is 273 instead of 272 (SWIR) or 955 (VNIR) we've usually seen.
Is it a fault or the wavelength number can be something other than 272 and 955?
The exact file is in 
```
/projects/arpae/terraref/sites/ua-mac/raw_data/SWIR/2016-11-02/2016-11-02__09-31-50-056/c268c7f7-f9e4-4181-838c-9327863dc4a2_raw
```
and the error message is generated by hyperspectral_workflow.sh by executing:
```bash
hyperspectral_workflow.sh -d 1 -i /projects/arpae/terraref/sites/ua-mac/raw_data/SWIR/2016-11-02/2016-11-02__09-31-50-056/c268c7f7-f9e4-4181-838c-9327863dc4a2_raw
```

Error Message:
```bash
Hyperspectral workflow scripts in directory /gpfs/smallblockFS/home/jiarunm/new/computing-pipeline/scripts/hyperspectral
NCO version "4.6.2-beta03" from directory /gpfs/smallblockFS/sw/nco-4.6.2-beta03/bin
Intermediate/temporary files written to directory /gpfs_scratch/arpae/imaging_spectrometer
Final output stored in directory /home/jiarunm/new/computing-pipeline/scripts/hyperspectral
Input #00: /projects/arpae/terraref/sites/ua-mac/raw_data/SWIR/2016-11-02/2016-11-02__09-31-50-056/c268c7f7-f9e4-4181-838c-9327863dc4a2_raw
trn(in)  : /projects/arpae/terraref/sites/ua-mac/raw_data/SWIR/2016-11-02/2016-11-02__09-31-50-056/c268c7f7-f9e4-4181-838c-9327863dc4a2_raw
trn(out) : /gpfs_scratch/arpae/imaging_spectrometer/terraref_tmp_trn.nc.pid48316.fl00.tmp
ERROR: Unable to identify camera type (SWIR or VNIR?)
HINT: hyperspectral_workflow.sh requires header file  to report either 272 (SWIR) or 955 (VNIR) or wavelengths. Actual number reported = wvl_nbr = 273.
```

**Comment by solmazhajmohammadi** [comment]
@FlyingWithJerome, 
New sensor has been installed on late October. 11/02 should be the first set of data with new sensor, all the data after Nov 2nd has been collected with 273 bands.  
I can look at the settings to see if we can reduce the spectral resolution to 272, if you think it is necessary.

**Comment by czender** [comment]
@solmazhajmohammadi @FlyingWithJerome It is not strictly necessary to use 272 instead of 273 bands in the hyperspectral workflow. However, changing from 272 to 273 means that no SWIR images from before 11/2 will be directly comparable (i.e., without interpolating wavelengths) to files after 11/2. If this is acceptable to @dlebauer and others, we will make the workflow work with either 272 or 273 SWIR wavelengths. IMHO changing wavelength grids should be a team decision involving domain scientists, not one imposed because it is technically expedient. Maybe this has already been discussed but it was a surprise to me :)

**Comment by czender** [comment]
We would also like clarity on whether the 273 wavelengths duplicate the 272 wavelength grid and add one more, or whether all 273 wavelengths are slightly shifted. This would help us understand whether interpolation or simple hyperslabbing are required to intercompare 272 with 273 wavelength images.

**Comment by solmazhajmohammadi** [comment]
@czender This was not a decision to change the wavelength grid. Unwanted change that happened when we got a new camera.
The wavelength spread(how many nanometers a given pixel represents) for the new camera is 5.90-5.91nm and for the old sensor is 5.914-5.920nm. And in total spectral resolution has been increased by 4.6190nm. 
linear interpolation between the two adjacent pixels can solve this.

**Comment by dlebauer** [comment]
I understand the new camera has very slightly different specifications, and changing the wavelength grid is imposed by the manufacturer. Summarizing from above:


* wider spectral range by (<4.62nm of ~1500 nm total)
* higher spectral resolution (narrower bands) (by <0.01nm  of ~5.6nm)
* more bands (273 instead of 272)

@czender to reply to your comment " IMHO changing wavelength grids should be a team decision involving domain scientists, not one imposed because it is technically expedient. "

Yes this is correct - I'll defer to Wasit (@remotesensinglab) for guidance. but here is are my initial thoughts: 
* Our [specification](https://terraref.gitbooks.io/terraref-documentation/content/data-product-creation.html) for level 1 data products is that the raw (level 0) be 'recoverable'. I interpret this as there should be no interpoloation or other processing in this step.
* We will need to develop workflows that allow comparison across data collected from different sensors anyway (e.g. among different sites or research groups). This is where the interpolation can be done (on the fly or as derived data products depending on user needs).
* Hopefully this use case will provide a first step toward generalizing the workflow to use sensor metadata to process data from different sensors (e.g. VNIR, old SWIR and new SWIR). 

@czender does this make sense ... scientifically and practically?
@remotesensinglab your thoughts?

**Comment by dlebauer** [comment]
@solmazhajmohammadi can you work with @craig-willis to put the metadata from the new SWIR into the appropriate location?

**Comment by czender** [comment]
That's all fine with me. I didn't know until yesterday that there would be other instruments with SWIR-like characteristics to intercompare with. NB: We already interpolate the Spectralon reflectance from the factory to the SWIR and VNIR grids, so it's nothing too new.

**Comment by rachelshekar** [comment]
@czender - can this issue be closed?
