### ISSUE TITLE
Extract lat/lon from metadata

### ISSUE THREAD

**Issue by robkooper** [terraref/computing-pipeline#27]
The JSON associated with the files uploaded will contain the lat/lon of the image. This information should be stored in such a way (GEOJSON + LD) that it can be rendered inside clowder.

**Comment by dlebauer** [comment]
Will add to Clowder as extractor: http://opensource.ncsa.illinois.edu/bitbucket/projects/CATS; #3 depends on this issue

**Comment by max-zilla** [comment]
There are two components that could be relevant to this:

I augmented **Clowder image extractor** to extract metadata from EXIF data embedded in images as well - [it is currently committed here](http://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/extractors-image/browse/metadata). This will automatically add any lat/lon fields to image metadata as part of the extraction, which could then be rendered with...

**Clowder Geospatial previewer** which looks for lat/lon metadata or geoJSON objects in file metadata to render at a Dataset level, effectively mapping any locations in all file metadata. I have committed [an initial version of this](http://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/browse/public/javascripts/previewers/geospatial-latlon?at=refs%2Fheads%2Flatlon_previewer) to my own branch. I plan to add JSON-LD component as well, and change map display from Google Maps to OpenLayers.

Work still remains in make sure these pieces connect and the data we receive from AZ is reporting lat/lon information in a way we can handle, but I believe this is heading in that direction.

**Comment by rachelshekar** [comment]
@dlebauer - what do we want to do besides put the geospatial info on a map?

Info for pixel lat/lon (not a flat plane) is different than global lat/lon

**Comment by max-zilla** [comment]
I have a [more official branch](http://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/browse/public/javascripts/previewers/geospatial-geojson?at=refs%2Fheads%2Ffeature%2FCATS-432-show-preview-map-of-geojson-metadata) now where I've ported the map to OpenLayers instead of GoogleMaps. 
![image](https://cloud.githubusercontent.com/assets/14166971/13221512/72507f5c-d941-11e5-9a7a-885b8a12ebd1.png)

Currently it'll display any GeoJson metadata it finds on the map, as well as any pairs of identified lat/lon pairs. This means we could mix things, e.g. an XY coordinate for a snapshot and a GeoJSON polygon representing the extent of the plot/relevant area for that snapshot.

No pull request yet as it's pretty basic right now - need to get some feedback before saying it's ready to be merged.
