### ISSUE TITLE
Prototype BRAPI interface

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#291]
Prototype a BRAPI interface to the TERRA-REF data. This will require mapping BRAPI concepts to the BETYdb model, implementing the API, and confirming conformance to BRAPI specification.

Completion criteria:
* [ ] Design documentation
* [ ] Create new tickets for downstream changes
* [ ] Stakeholder review

**Comment by max-zilla** [comment]
Relevant: https://docs.google.com/spreadsheets/d/1ykPJWi0kLSYXUV86U54E9SLuypBMoJUuJTkdpcxuU1g/edit#gid=0

**Comment by dlebauer** [comment]
Here are a few open, live BRAPI examples (responses from users on the BRAPI mailing list)

---

from Cyril Pommier

You can use our current implementation of the Phenotypes call on GnpIS where you can have access to Wheat and Grapevine data.
This will allow you to get phenotyping observations from a single study or several studies in several locations and years.
You can have access to the full list of our webservices in SWAGGER : https://urgi.versailles.inra.fr/ws/swagger-ui/index.html#/Breeding_API

Please note that some adjustements are on the way to fully adjust those calls to BRAPI V1 which has been frozen at the end of 2016.

Don?t hesitate if you have any questions or remarks.

---

from Nick Morales

We have a few open access databases that you could work with, the largest one being cassavabase.org.
Due to the size of cassavabase.org it is often a bit slow (something we are obviously working to fix), so another database you could use is sweetpotatobase.org

It sounds like you want observations with experimental context, which a call such as https://sweetpotatobase.org/brapi/v1/studies/158/table provides.

This is a work in progress certainly, but any feedback is much appreciated.

As I'm sure you know, you can view the calls we have implemented (to one degree or another) using cassavabase.org/brapi/v1/calls

**Comment by craig-willis** [comment]
I will be at the BRAPI hackathon all next week.  More to come.

**Comment by craig-willis** [comment]
@nfahlgren or @dlebauer 
Looking at the BrAPI Germplasm call, for example:
http://docs.brapi.apiary.io/#reference/germplasm/germplasm-details-by-germplasmdbid

Do we have information for the fields marked MCPD aside from what's in Genesys?  For example, acquisitionDate, seedSource.

**Comment by dlebauer** [comment]
@craig-willis we do have and/or can get this information: @nshakoor should have this information if not Noah. Do you need it today or just want to know if it exists?

**Comment by nfahlgren** [comment]
@craig-willis @dlebauer can we add/update the fields here (https://docs.google.com/spreadsheets/d/1ntnps0u0c8O4xxrv_VVqfxDkpmppCGdFIIWLMmRCeSM/edit?usp=sharing) that you are looking for?

**Comment by craig-willis** [comment]
Thank you -- I just need to know that it exists for now.  I'll add to the spreadsheet.

**Comment by max-zilla** [comment]
@craig-willis please update

**Comment by craig-willis** [comment]
Closing this.  Will create separate new issues for more recent activity.
