### ISSUE TITLE
Protocol for pushing data to NCSA using REST interface

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#3]
After a user or sensor platform generates a packet of data, they will need to push the contents NCSA.

* [x] what should meta-data look like? i.e. ghs data similar to json files proposed for field system (terraref/reference-data#2)
* [x] how should data be prepared (compressed? identified?)
* [x] once prepared, how should it be pushed? What permissions are required?
* [x] add end user documentation to github.com/terraref.documentation (or https://dlebauer.gitbooks.io/terraref-documentation/ for a nice online gui editor)
  * what information does Danforth and MAC need to push data
  * this is the clowder protocol
* [x] @max-zilla please discuss options with @nfahlgren for pushing from Danforth, possibly setting up a live stream for testing at some point. 
* [ ] identify if collections can be defined by some tag / feature in metadata (add feature request to Clowder)
* [ ] @nfahlgren send raw image files to @robkooper to evaluate existing extractors

**Comment by max-zilla** [comment]
see this issue for some discussion of GeoJSONas a potential delivery format
https://github.com/terraref/reference-data/issues/2

Some key aspects to this:
* How should the metadata be sent with an image?
  * Each file.img has a file.json sent along with it, and Clowder extractors pull metadata from the .json file and associate it with the .img file
  * Metadata is sent in a followup API call after file.img is sent, directly associating blob of GeoJSON data with the img file under a "geojson" metadata field
  * Metadata is sent in a followup API call after file.img is sent, with each relevant field (e.g. "camera ID": 1234") being assigned to a corresponding individual metadata field
  * Metadata is embedded in the image somehow, e.g. as EXIF data

If Danforth is already preparing to push data as JSON, options 2 and 3 would seem preferable as they cut the number of files by half (don't need the .json files). Would there be concern about connectivity if we relied on getting a response back that the image was posted before posting the associated metadata? do we risk 'orphaned' images if the connection breaks, or is that the least of our worries?

**Comment by doctorroboto** [comment]
How is the LemnaTec system doing this, or rather, what's the preferred
approach? Do we want to adopt the same strategy, or push them in a certain
direction?

**Comment by max-zilla** [comment]
I uploaded 2 sample files to #15 that illustrate API POST calls using Python and cURL. Not documentation yet, but it's something.

**Comment by dlebauer** [comment]
@doctorroboto the Lemnatec Indoor system currently stores metadata in a PostgreSQL database as well as folder and image names.

A metadata format for the Lemnatec Field system has been proposed and iterated over in terraref/reference-data#2 but has not yet been fully flushed out and is currently waiting on feedback and revisions from Lemnatec.

**Comment by max-zilla** [comment]
A rough outline and an expansion on some of the questions raised above has been added here: https://github.com/terraref/computing-pipeline/blob/master/CLOWDER%20GUIDE.md

I'll be augmenting this document as we continue discussions.

**Comment by max-zilla** [comment]
Started discussions with @nfahlgren via email:

The script I prepared is stored here: https://github.com/terraref/computing-pipeline/blob/master/scripts/TERRAClowderUploadPython.py 
 
The python version is the one to look at for now. There’s also a bash script but it needs to be updated – the API recently changed so you can’t POST a file directly without creating a destination dataset first, so I’ll need to expand that one if we decide to use it.

Right now, the Clowder instance in the code is the Terra Ref instance: http://141.142.208.144/clowder/ 

To test this out….
1.	Add your username and password to lines 8 and 9
2.	Add a pointer to some snapshot directory in line 16
3.	If your files are PNG, change line 29 to “.png” instead of “.jpg”  (I’ll change it to look for either/both)
4.	Try running the script (for Python 3.x - You’ll also need [Requests](http://docs.python-requests.org/en/latest/) installed (or pip install requests)
5.	The script will create “Test Dataset” and add all the images in the directory to it. (Test Dataset can be replaced with a better dataset name eventually)
6. This instance of Clowder has the PlantCV extractor enabled, so all the files uploaded should have the ~5 PlantCV output thumbnails you saw yesterday.
                                                (In Clowder, Datasets > Test Dataset > Files tab > click a filename)

Right now, my code does not include a metadata object in the POST. The request is formed in line 31:
```python
r = sess.post(clowder_url+"api/uploadToDataset/"+ds_id, files={"File" : f})
```

I’m currently in discussions with the team to determine if we can attach the metadata in a single call. In my previous code, I would follow up the metadata in a second call after receiving a 200 response:
```python
if r.status_code == 200:
file_id = r.json()["id"]
print(files[curr_f]+" successfully uploaded. Adding metadata to ID "+file_id+"...", end="")

headers = {'Content-Type': 'application/json'}
md_url = clowder_url+"api/files/"+str(file_id)+"/metadata
md_data = {metadata JSON goes here}
md_r = sess.post(md_url, headers=headers, data=json.dumps(md_data))
```
…this is still possible, but I’m hoping I might find a solution that only requires a single call instead of 1. Send file 2. Send metadata. This can be our fallback approach in the short-term however.

Once you’ve gone through this exercise to verify it worked at a basic level, we can start to refine. Among the ideas I had:
•	Simulate some metadata and get that part plugged in (see above)
•	Integrate the piece that queries the Postgres DB periodically  and extracts relevant metadata at your end
•	Determine naming convention for a Dataset – I imagine snapshot #### is not the preferred name going forward
•	Do some load/delay testing to see how it handles 10, 100, 500 file batches (not necessarily in same folder)

**Comment by robkooper** [comment]
Should also look at [pyClowder](https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/pyclowder/browse) since this hides some of the complexities of talking to clowder behind a python api.

**Comment by max-zilla** [comment]
@robkooper It may make sense to expand pyClowder's capabilities for this. There is upload_file_to_dataset() in **extractors.py**, but in **api.py** there is only upload_file() which may be getting deprecated at this point (expects a secret key and posts directly to /api/files).

I think for @nfahlgren's use case, adding create_dataset() and upload_files_to_dataset() to **api.py** could be sufficient. I'll need to talk to Luigi or Smruti about how to handle a secret key vs. user credentials - the script I refer to above just uses a name and password for Clowder to authenticate the request.

**Comment by robkooper** [comment]
Yes, I agree. I think it would be good to add that to the code. It would be nice to allow you to either pass in a key, or a username/password combo and it will pick them appropriately (I would say username+password over key if both specified). Then in the extractors/upload_file_to_dataset we can just call the real function in api. Might want to slowly over time deprecate some of the functions there and only keep the real extractor parts in there.

Also we should probably have a datasets submodule, and file, etc.

**Comment by max-zilla** [comment]
Opened a PyClowder pull request with this functionality to make things simpler for @nfahlgren.

https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/pyclowder/pull-requests/9/overview

**Comment by max-zilla** [comment]
@nfahlgren and I will be discussing this on a call at 1pm today.

I have two pull requests that @robkooper needs to approve before the simpler files+metadata API call is available:
- [Clowder API component] (https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/pull-requests/684/overview)
- [PyClowder python connection into that new API component](https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/pull-requests/684/overview)

In the meantime we can use my python script described above which handles this in 2 steps for testing. There will be a meeting with Globus today as well. I believe we initially were considering Globus for the MAC transfer, but perhaps it will end up making sense for Danforth as well. For now I'm assuming we will not use Globus for Danforth right away.

**Comment by nfahlgren** [comment]
@max-zilla last Friday we got a Globus endpoint setup on our system, so it is ready if we want to use it for the image transfers from Danforth.

**Comment by max-zilla** [comment]
@nfahlgren and I just spoke on the phone. For now, the feeling is that Globus won't really be necessary for ~300 images/hour from Danforth. The general plan is:

1. Before the API enhancement pull requests are approved, I propose putting the file+metadata transfer code out on the Terra dev instance (http://141.142.209.122/clowder/) so that Noah and I can use it to get the API transfer process locked in with data/metadata Noah has on disk. I will pick @robkooper's brain about how to handle this as that test branch is currently synced to the VM tool launcher demo - there might be a better solution.

2. After that, get Clowder-specific PlantCV scripts working to handle outputs. With 1 and 2, we aim to guarantee actual data that people can send or see for the summit.

3. Once these are in place, Noah will finish out the automation piece that handles monitoring and transfer of images as they arrive in the Danforth database.

Plan to start putting these pieces in place Wednesday 1/27.

**Comment by robkooper** [comment]
wrt 1. we can make a special branch that has multiple branches merged for deployment on the dev server.

**Comment by max-zilla** [comment]
we now have an API to start pushing some files into.
http://141.142.209.122/clowder/
This is the dev instance for TERRA. In the upper-right you can click Login then sign up.

Noah will be starting transfer tests shortly.

**Comment by robalba1** [comment]
Hi Max,

This is great!  Keep us posted as your testing results come in.

Rob

**Comment by nfahlgren** [comment]
I have the basic workings of the script done to push data from the Danforth Center (https://github.com/terraref/computing-pipeline/blob/master/scripts/PlantcvClowderUploader.py). It creates a collection first to contain all the datasets uploaded for an experiment. It creates a dataset for each snapshot and uploads all the images associated with a snapshot to the dataset. I uploaded a test data set and it seems to all be working. 

The next part is to add metadata to each dataset. Do I use the add metadata or add user-metadata API call for that?

**Comment by max-zilla** [comment]
Previously, you would've needed the add metadata API call. However, I've expanded the api/uploadToDataset endpoint to support sending metadata in the same call as the file.

I think the easiest route would be to expand your upload_file_to_clowder() function to also take the JSON metadata for the file, and send that in your POST on line 218. Something like this should work:

```
md = {"metadata1":100, "metadata2": 200}
r = sess.post(clowder_url+"api/uploadToDataset/"+ds_id, files={"File" : f}, data=md)
```

Let me know if this isn't behaving as you'd expect and I can help to nail down the syntax. Generally we can accomplish this in the same call however.

**Comment by robkooper** [comment]
user metadata is more intended for a claim a user makes and is always associated with a user. So for example you add your description to an image. Metadata is used for those that are not created by user but is either information you have beforehand (type of instrument etc), or information that is extracted (as done by plantcv).

**Comment by dlebauer** [comment]
We should also require terms of use / license / copyright for all datasets.
Defaults for the Cat 5 products should be CC-By, but streams that we do not
set up should require terms of use in metadata. We can chat further (among
us, w/ library and collaborators) about details. @robkooper, how does SEAD
handle this?

**Comment by robkooper** [comment]
Only when publishing to certain places does SEAD require specific licenses. I can setup the system to default to cc-by as the license if that is what we want. The default right now is copyrighted by the uploader. If we want to change it, we should make it clear to all users.

**Comment by dlebauer** [comment]
Or perhaps just require it be specified and use cc-by when setting up pipelines.

This is related to https://github.com/terraref/reference-data/issues/8

**Comment by dlebauer** [comment]
https://github.com/terraref/computing-pipeline/blob/master/scripts/PlantcvClowderUploader.py

https://github.com/terraref/computing-pipeline/tree/master/scripts

**Comment by max-zilla** [comment]
From @nfahlgren vial email on 02/10/16, for posterity:

I have been working on the metadata component of the data transfer. I split that into two parts: 1) user-provided experimental metadata; 2) metadata automatically provided by the LemnaTec system. #2 is easy and just requires some reformatting. I am planning on attaching metadata for #2 on each image record using the API call you provided. For #1 I have worked out a draft template that users would fill out to provide us with metadata that they need to provide. It almost certainly needs to be changed in many ways, but I set it up in JSON and added a method to parse it and upload the metadata to each Clowder dataset. Here is an example of what the JSON could like:

```
{
    "experiment" : {
        "planting_date": "2014-09-18",
        "title": "Test upload",
        "author": "Noah Fahlgren",
        "project": "TERRA-REF",
        "location": "Donald Danforth Plant Science Center",
        "instrument": "Bellwether Phenotyping Facility",
        "growth_medium": "MetroMix360 potting mix with Osmocote"
    },
    "sample" : {
        "barcode" : {
            "format": {
                "species": "0-1",
                "genotype": "2-4",
                "treatment": "5-6",
                "unique_id": "7-12"
            },
            "species": {
                "Ca": "Camelina sativa"
            },
            "genotypes": {
                "031": "NF0000031",
                "002": "NF0000002"
            },
            "treatments": {
                "AA": "100%: 217 ml water (48% VWC)"
            }
        }
    }
}
```

We may want to include some [JSON-LD context[(https://en.wikipedia.org/wiki/JSON-LD) to help others understand these metadata - for instance, is there a sensible page to point to to help one understand those genotype codes? This is not strictly required for every single field, but Clowder supports the LD format so there are likely some low-hanging fruit to address.

**Comment by max-zilla** [comment]
Some ideas when thinking about what we might do with JSONLD looking at the example json above...

- Have a context link for "experiments" (e.g. http://terraref.ncsa.illinois.edu/experiments) where we can explain a bit about that experiment object - what does growth_medium mean here? what does location mean (i.e. it's a research facility rather than XY coordinates)? So that my grandma could explain what those values really mean - "Noah planted in this medium on this date and ran it through this scanner at this location"

- somewhere that defines each of the barcode components. it can be as simple or technically detailed as necessary - I'm guessing that the two barcodes here when computed are Ca013AANF0000031 amd Ca002AANF0000002. We have a link describing how a barcode consists of those things, also saying what we mean by species, genotypes and treatments in this case. 

- this does not all have to be bespoke references - for example, it would be cool if under "species" there was a "symbol" field that said CASA2 so we could point to http://plants.usda.gov defining [what a symbol is](http://plants.usda.gov/faq.html#symbols), so that researchers end up finding http://plants.usda.gov/core/profile?symbol=casa2. Similarly it would be fine if there are authoritative sources defining a species (found [this](http://useast.ensembl.org/info/about/species.html?redirect=no) for vertebrate genomes) or a genotype, but we start to build a nice thread to unravel for the curious.

**Comment by nfahlgren** [comment]
@max-zilla I just pushed a new version of the PlantcvClowderUploader.py script. It is able to attach metadata to a dataset but uploading metadata with files is not working for me (I don't get an error but don't see the metadata either).

**Comment by max-zilla** [comment]
@nfahlgren the metadata JSON needs to be itself in a JSON object with the filename as the key - this is so that one can upload 2+ files and metadata in a single call if desired.

Try changing line 117 to:
```
upload_file_to_clowder(sess, args.url, image_path, ds_id, {img_name: img_metadata}, args.dryrun)
```

**Comment by nfahlgren** [comment]
@max-zilla that works (no errors) and makes sense but I still don't see the metadata on Clowder at the file level. In trying to simplify testing, I did this (leaving out username, password and URL):

```
import requests

session = requests.Session()
session.auth = (username, password)

f = open('VIS_TV_z1_h1_g0_e82_117887.png', 'rb')

resp = session.post(url + "api/uploadToDataset/56c34e89e4b0627842cae253", files={"File" : f}, data={'VIS_TV_z1_h1_g0_e82_117887.png' : {'metatest' : 'testvalue'}})
```

This returns status code 500. Maybe I'm not setting the file and metadata keys correctly?

**Comment by max-zilla** [comment]
@nfahlgren the JSON metadata for each file needs to be string-encoded. I think all you need to do is:

```
import json
...
resp = session.post(url + "api/uploadToDataset/56c34e89e4b0627842cae253", files={"File" : f}, data={'VIS_TV_z1_h1_g0_e82_117887.png' : json.dumps({'metatest' : 'testvalue'})})
```

Basically, wrap the md for each file in json.dumps() to stringify it. Also if you're only passing one file, you can simplify your code by using the same key for metadata instead of filename. So in your example, 
```
data={'File': json.dumps(json_md)} 
```
...should work just as well as using the filename instead of 'File'.

**Comment by nfahlgren** [comment]
Thanks @max-zilla that did the trick. I just pushed the new working version.

**Comment by nfahlgren** [comment]
The sorghum pilot experiment from the Danforth Center indoor system is uploading now. Can you all see it or do I need to share it somehow?

**Comment by dlebauer** [comment]
I am looking at http://141.142.209.122/clowder/collections and don't see it the files. Is that where you are pushing to? @max-zilla or @robkooper how can we make the data that Noah is pushing publicly accessible?

**Comment by nfahlgren** [comment]
@dlebauer I created a space called "Danforth Center Phenotyping Facility" and added the collection for the sorghum pilot experiment to it. I added everyone to the space, can you see the collection now?

I had to start the transfer over because I ran into a problem. I realize I need to add in the ability to restart the transfer without having to start over.

**Comment by dlebauer** [comment]
I can see the collection but when I try to open it I get

'You are not authorized to access dataset "snapshot295493"'

This is the same behavior I get with the data Max posted; perhaps an issue
with Clowder.

**Comment by robkooper** [comment]
datasets need to be added to a space as well for the permissions to be applicable.

**Comment by dlebauer** [comment]
OK. Is there an easy way to add datasets to the space? Should there be default inheritance (of permissions and datasets)? Here are the issues I've found:

1. I have permission to a collection but not a dataset

On the ["tool test" page](http://141.142.209.122/clowder/collection/56ce0960e4b0ed49ad02f59e), there are two links "users who have access to this [dataset / collection]. I am listed as having access to the collection but not to the data set. 

If a user is given permission to a collection, should they also be given permission to the datasets that it contains (similarly, if given permission to a space, should they get permission to the spaces' collections too?

2. datasets in a collection are not inherited to the parent space:

On the ["Danforth Phenotyping Facility Collection" space](http://141.142.209.122/clowder/spaces/56d3cd8be4b0c7e3b16747ac), there is one collection there are no datasets associated with the space. The collection is the [Sorghum Pilot Experiment](http://141.142.209.122/clowder/collection/56d3ce9ce4b0c7e3b16747cd). When I click that link to open the collection there are lots of datasets listed.

If a collection has a data set and a collection is added to a space, shouldn't the datasets also be added to that space? Or is that not desired behavior?

**Comment by max-zilla** [comment]
@nfahlgren in the short term you can go to the [Danforth Center Phenotyping Facility collection](http://141.142.209.122/clowder/collection/56d3ce9ce4b0c7e3b16747cd) you created, click into a few of the snapshot datasets, and add the snapshots to the DCPF space. This is show David can show some of the snapshots this week in discussions if he wants to.

In the medium term, we can use a script to associate all your snapshots with the space so that everyone has access, and/or have the Clowder team discuss whether the propagation of these permissions should be adjusted.

**Comment by robkooper** [comment]
I would love to hear what people have to say about the permissions. Our thinking is that datasets and collections should be treated as separate entities for security. The reasoning is that is the following scenario:

There are 3 users, A, B and C, and 2 spaces K and L. User A and B are part of space K and users B and C are part of space L. 

User A uploads a dataset and adds it to space K. Only users A and B can see this dataset. User B creates a collection, adds this collection to space K and adds the  dataset. Nothing has changes, only users A and B can see this dataset.

User B adds the collection to space L. Now users A, B and C can see the collection. This is fine since the creator of the collection decided to share the dataset with all other users.

The question is should user C see the dataset as well? User A who is the owner of the dataset might never have intended for a dataset to be shared with user C. By using the permissions of the collection and not those of the dataset, user C can see the dataset.

If we use the permissions of the dataset and collection separately we will have the intended solution.

Let me know what people think @nfahlgren @dlebauer @max-zilla @robalba1 @doctorroboto

**Comment by nfahlgren** [comment]
@dlebauer @max-zilla adding some now.

**Comment by nfahlgren** [comment]
2,725 snapshots containing 10 images each were uploaded in 775 minutes (3.5 snapshots/minute). I am running a script to add each dataset (snapshot) to the shared space, so @dlebauer you should see them all soon.

**Comment by dlebauer** [comment]
@nfahlgren this was really great. However, the PlantCV pipeline was not triggered. Is this a bug (@max-zilla, @yanliu-chn)?

**Comment by robkooper** [comment]
They are triggered, there is no extractor running right now. There is 33,821 datasets waiting to be processed right now. Might be a good use case for the scalability tests that @yanliu-chn has been doing.

**Comment by max-zilla** [comment]
Closing this issue. Discussion can move to #68. Will move some info to my documentation.
