### ISSUE TITLE
Review of full field stitched data

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#306]
Now we have the full field stitching pipeline, it would be great to review the algorithm. 

### Dealing with sun/shade:

* Could we do a better job of accounting for exposure when converting 16 bit .bin to tif files?
* Where there is overlap, can we select the best or do something more sophisticated when merging 
* Or would it help if the scans were done at a time during the day when there was less shade (e.g. in the AM)? 
* Or if the scans were done 2x during the day to make sure we have the entire area in only sun or only shade?
 
<img width="696" alt="screen shot 2017-05-04 at 11 34 52 am" src="https://cloud.githubusercontent.com/assets/464871/25714517/e2973d6c-30bd-11e7-9f7e-995b11af9fc5.png">

```
terraref/sites/ua-mac/Level_1/fullfield/2017-04-27/
```

**Comment by pless** [comment]
_Could we do a better job of accounting for exposure when converting 16 bit .bin to tif files?_
a) We could.  First, if the data is going to be used directly for downstream processing, we should produce 16 bit tiff files so we don't lose data there.  Second, we could do a variant of high-dynamic range rendering --- IF the areas are washed out are just because the screen shows 8 bits of resolution, this is a way to try to show 16 bits of data on a regular screen.  I don't think that is the case here; because things are washed out, the data is really missing.

_Where there is overlap, can we select the best or do something more sophisticated when merging_
We can select the best, or, probably have some simple rule like "take the darkest pixel".  There are more clever things we could do if we wanted to make this montage look amazing and hide the boundaries, but those steps could introduce artifacts that make downstream processing harder.

_Or would it help if the scans were done at a time during the day when there was less shade (e.g. in the AM)? ... Or if the scans were done 2x during the day to make sure we have the entire area in only sun or only shade?_

Both of these would keep the data more consistent.  My belief is that it would be hard to be entirely consistent, so any algorithm will eventually have to deal with harsh shadows in the images.  If that is the case anyway, perhaps it isn't so important? --- or at least this is not a hard requirement that mandates the scheduling of the entire gantry.

**Comment by dlebauer** [comment]
@pless and @ZongyangLi What are the next steps? 

There was a related discussion on using feature matching starting at https://github.com/terraref/computing-pipeline/issues/265#issuecomment-292232377

**Comment by dlebauer** [comment]
@pless and @ZongyangLi can you comment on the compressed files that @jterstriep generated? Some have 25x size reduction.

**Comment by max-zilla** [comment]
@ZongyangLi @pless @dlebauer I generated a VRT, TIFF and 10% resolution TIFF for 05/09. There are plants in this one. More interesting light effects too, in the north half this time.
![screen shot 2017-05-12 at 1 58 51 pm](https://cloud.githubusercontent.com/assets/14166971/26012731/28bfc49a-371b-11e7-83f4-e577fd9648bb.png)

**Comment by dlebauer** [comment]
@ZongyangLi can you please create a new issue that covers the implementation of these changes, and then close this one?

**Comment by rachelshekar** [comment]
@ZongyangLi - reminder

**Comment by ZongyangLi** [comment]
further work will discuss in #326
