### ISSUE TITLE
Increase exposure time for hyperspectral camera

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#334]
To compensate for most images being in the shade.
@czender - please add additional information here.

**Comment by czender** [comment]
This issue is based on a question I asked: given that so much of the image is shadowed, and looks fairly dark in the visible, does it make sense to increase the exposure time to get brighter images in the shadowed portions? One downside would be over-exposing the sunlit portion. Another is that @solmazhajmohammadi said, IIRC, that the exposure time cannot be increased beyond 45ms, which it is currently operating at.

**Comment by SolmazHajmohammadi-LemnaTec** [comment]
I think Stuart was able to increase the exposure time up to 65ms. But this will mess up the triggering signal and data will be downsample by a random factor.

**Comment by craig-willis** [comment]
This is a stale issue with no comments in last 2 months. Please create new issues if work remains or put this content in the documentation.
