### ISSUE TITLE
Georeference LAS files

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#363]
Per https://github.com/terraref/reference-data/issues/185#issuecomment-331208513, we need to translate the PLY coordinates to lat/long coordinates in ply2las extractor. Currently, the files use the point-cloud reference, which isn't right.

Completion criteria:
* [ ] Update ply2las extractor to create merged LAS file in lat/long
* [ ] Update plant_height extractor subset the LAS files  by plot so we can push traits to BETYdb by plot
* [ ] Code review (pull request)
* [ ] Create sample data
* [ ] Review sample data

**Comment by ZongyangLi** [comment]
During the past few days, I did a bunch of tests for georeferencing las files. Since there is no further comment from @jterstriep ,@yanliu-chn , it's not quite clear for me if I am in a right way. Any suggestion is welcome if you have experience in georeferencing las files.

I will list all the potential options below and try to explain the blocking for each option.

1. [x,y,z] to [lon, lat, elevation] for each point
I totally agree this might be suitable for a subsetting plot level point cloud task, but I will prefer a pure point cloud coordinate without another translate when I use las file. Still I try this, but not succeed. The length of bit for each XYZ coordinate is 32 bit long integer, so the region for X would be [-2147483648, 2147483648]. The accuracy of laser scanner is 0.01mm, then for a UTM coordinate[408987, 3660091], it requires for a region of[4089870000, 36600910000],  which is far beyond the limitation. when I test this, it continues to return a unreasonable value after the translating.

2. Then I try [x,y,z] to gantry [x,y,z] for each point, it works in this way:
![translate_each_point_to_gantry_axis](https://user-images.githubusercontent.com/20230686/31197561-2012464c-a917-11e7-8b97-190c31facc9b.png)

3. Another option is just modify the offset in the header file, it still works well in [x,y,z] to gantry [x,y,z]:
![header_gantry](https://user-images.githubusercontent.com/20230686/31197780-c73d2d2e-a917-11e7-8f00-61545d3e8574.png)
But it failed when I tried [x,y,z] to MAC[x,y,z], only a few of points remain, I will say it's because of a down accuracy data missing:
![header_mac](https://user-images.githubusercontent.com/20230686/31197896-2e4c64ee-a918-11e7-82e6-52ff679aac37.png)

@dlebauer That's the situation for now, if the option 3 works for you([x,y,z] to gantry [x,y,z] only modify header), I will upload my code to Github.

Other issue(or further idea):
1. LAS files is far more structural than ply, more data can be store in LAS, it's not smaller than ply, @solmazhajmohammadi , a merged las is more than 1.7GB while two plys are less than 0.7GB.
2. LAS now has 4 version of header format and 10 different point format, we are now using header format 1.2 and point format 3. 
3. LAS to plant_height would be another extractor when we decide which option should be used, it should not be here. @craig-willis

**Comment by dlebauer** [comment]
I think that for now, if the point clouds can be in gantry[xyz] that will be a good first step, and would be the minimum requirement for a data product sufficient for the first data release. 

I am a little confused about how scale and offset work. Is it possible, for example, to have all points in the range [0, 100] and then provide values of scale and offset that would allow users to translate to lat,lon, height?

**Comment by ZongyangLi** [comment]
@dlebauer 
In part 2 of option 3, I kind of show the example of providing UTM 12 scale and offset. Let me explain more what I learn in recent days.

In LAS Point format 3, which we are using now, there are 3 different field name: X,Y,Z relate to the coordinate. X, Y, Z are 32bit long integer(if someone is able to convert it to 64bit data, please point me out how could I get that). Remember our resolution of laser scanner is 0.00001 meter, so the limitation range now is [-214748.3648, 214748.3647] meters. If I set the offset to [408987, 3660091] meter which is our MAC coordinate, it will over the limitation. The example of setting offset to [408987, 3660091]m is this picture:
![header_mac](https://user-images.githubusercontent.com/20230686/31233707-d4e2c916-a9b2-11e7-8c1b-dde902c93f2f.png)
It seems to me that LAS will automatic cut the low bit of data, so only a few X, Y, Z remain in the picture, the resolution is set to 0.1 meter, all points under 0.1m will disappear. It's the same if we use lat/lon, we will lose our high resolution data.

**Comment by dlebauer** [comment]
@ZongyangLi thanks for the clarification - I didn't realize that in this last example you had used the scale and offset. I had assumed that the data could be stored in smaller values and that the software would automagically handle the scale and offset. Would it be an option to provide the data in gantry[xyz] and then provide the UTM scale/offset in a descriptive metadata field?

Page 2 of the [LAS 1.4 specification](https://www.asprs.org/a/society/committees/standards/LAS_1_4_r13.pdf) says that it supports 64 bit floats. However, if this is a non-trivial task and / or further inflates these files then I this may not be an ideal solution.

**Comment by ZongyangLi** [comment]
@dlebauer I had uploaded my codes to https://github.com/terraref/extractors-3dscanner/blob/master/ply2las/ply2las.py
It's just a las to las convert now, I think we could provide UTM offset in the VLR descriptive metadata field.

Thanks for pointing me out 64bit is available in LAS 1.4, actually when I discuss with @pless this Monday, we agreed that we should use LAS header format 1.4 and point format 6. Not clear now if LAS 1.4 is the same as header format 1.4, and whether my current lib `laspy` works for this.

**Comment by max-zilla** [comment]
@jterstriep

**Comment by jterstriep** [comment]
LAS 1.4 does not support 64bit for x,y,z coordinates regardless of point format. I think the 64bit referenced on page 2 is only talking about indexing and offsets not the actual point data.

**Comment by max-zilla** [comment]
@ZongyangLi I am implementing your code above for LAS 2 LAS conversion and should have some tests ready later today. @jterstriep and I took a look yesterday.

I am going to replace one piece of your code - get_origin_utm_coordinate() - because we are using that same formula in our metadata cleaning so we can reference that and you don't have to generate again.

**Comment by max-zilla** [comment]
Implemented the ply2las code w/ metadata reference in this merged PR:
https://github.com/terraref/extractors-3dscanner/pull/11

**Comment by ZongyangLi** [comment]
@max-zilla May I take a look at the reference code about replacing the piece of `get_origin_utm_coordinate()`
This function is the key translating formula from ply coordinate to gantry coordinate as mentioned in https://github.com/terraref/documentation/issues/162
I just want to make sure it's the same.

**Comment by max-zilla** [comment]
@ZongyangLi code is here:
https://github.com/terraref/terrautils/blob/master/terrautils/lemnatec.py#L806

I believe only difference is incorporation of 'location in camera box' offset applied to locations.

**Comment by dlebauer** [comment]
this has been completed ...

**Comment by dlebauer** [comment]
Closing per https://github.com/terraref/computing-pipeline/issues/405#issuecomment-407089030
