### ISSUE TITLE
Update terrautils pypi package to use terraref namespace

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#429]
Following on from #404, use the new namespace going forward.

Completion criteria:
* [x] Tag github for 1.1.0 release
* [x] Update package spec and setup.py
* [x] Update documentation
* [x] Push to pypi (v.1.1.1)

**Comment by max-zilla** [comment]
Updated the PR: https://github.com/terraref/terrautils/pull/46

I pushed 1.1.1 then had to update setup.py a bit further because there was an old reference to description.rst and now it's readme.rst. So it's 1.1.2 is latest.

To be consistent going forward the package name also was updated:
https://pypi.python.org/pypi/terraref-terrautils

(terraref- prefix like the science packages)
