### ISSUE TITLE
Monitor Gantry Cache Server - Design 

### ISSUE THREAD

**Issue by sbrad77** [terraref/computing-pipeline#517]
### Discussion Needed
The cache server does not reside at NCSA
Who should be monitoring the cache server - local at Maricopa or NCSA
What should be the monitoring mechanism
What should be monitored - what subdirectories, space, load, etc.
What should the appropriate thresholds be

CheckMK monitoring for automated cleaning service - if it crashes, get alert

**Comment by max-zilla** [comment]
@robkooper @tcnichol and I will sit down for meeting to design what this monitor looks like - initial suggestion, alert triggers if gantry >= 85% full.

**Comment by jdmaloney** [comment]
Alerts have been integrated into the #alerts slack channel.  Currently monitoring:
- Local Disks (when above 85% used)
- Load Average (alert when it crosses 30)
- Memory (when it crosses 95% used)
- Network Interface Errors (checks if error counters are increasing)

@robkooper or @max-zilla If you have something else you want me to add let me know, otherwise will close this hear end of today.

**Comment by jdmaloney** [comment]
I've also added monitoring of the vsftp server (the vsftpd processes) and the globus-gridftp-server service.  Alerts will hit slack if either of those services are unhealthy and not in the "active" state according to systemctl
