### ISSUE TITLE
Design next version of BETYdb API

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#52]
* [x] Modify limit option to be more usable
* [x] Add comments to API code [used apipie; need more comments for uploading traits]
* [x] Get beta API ready for prime time, merge into master branch and deploy

* Extract API from main controller code. Suggested by @robkooper will make a cleaner code.
* Revise API.
* Next step to meet to define specifications.
* See PecanProject/bety#381

**Comment by dlebauer** [comment]
@gsrohde could you please summarize your updates and any outstanding questions from the last meeting ([notes are here](https://docs.google.com/document/d/1ffVqRJgXx6p2idW4RgDbDz6UopxNljzCHnLUjw02qy8/edit)) here and bring them up at the meeting Thursday?

**Comment by gsrohde** [comment]
I've created a full-fledged draft API for inserting trait data from an XML file.  This includes:
* Effective defaulting, so that species, site, citation, and date-time (for example) can be specified for groups of traits and not have to be repeated for each trait.
* The ability to specify associations using any unique set of column values; for example, a citation can be specified using a doi value or a combination of `author`, `year`, and `title`; the `id` of the matching citation will be used as the value of `citation_id`.
* The ability to link traits to entities.
* The ability to specify one or more covariates for each trait.
* Specification of the XML data file format with an XML schema; other developers should be able to check their XML data files using command-line tools if desired.

This draft code is deployed to http://pecandev.igb.illinois.edu/beta.  Instructions for testing out this API follow in the next comment.

**Comment by gsrohde** [comment]
#### Testing out the API

To try out the API for inserting traits, try this:

1. Copy `TEST_XML_DATA` from https://github.com/PecanProject/bety/blob/draft_insertion_api/api_stuff/TEST_XML_DATA
2. In the directory where you saved this file, run

    ```
    curl -X POST --data-binary @TEST_XML_DATA pecandev.igb.illinois.edu/beta/api/v0/traits.xml
    ```
This should return a JSON response listing the ids of the traits that were inserted.  (Entities and covariates were also inserted, but these aren't (yet?!) listed.)
3. In a browser, go to http://pecandev.igb.illinois.edu/beta/traits/99000000023, replacing "99000000023" with any of the numbers listed in the JSON result.  You should see the information corresponding to what was in `TEST_XML_DATA`.  Note that the third id corresponds to a trait having some covariates, which you should also see.

4. If you have access to the PostgreSQL databases on pecandev, go to the
`bety_beta` database and run
    ```
    select * from entities order by id desc;
    ```
You should see four newly-created entities (identifiable by the "created_at"
column value).  Three are anonymous, but one has a name and notes taken from the
`TEST_XML_DATA` file.
5. You can tweak the `TEST_XML_DATA` file or make your own file from scratch and run the
curl command to insert the data in it.  To test the format of the XML file, you can validate it
manually on the command line as follows:

    a. Copy the schema files TraitData.xsd and TraitAttributeTypes.xsd from
https://github.com/PecanProject/bety/tree/draft_insertion_api/api_stuff to the
same directory that contains your data file.
   b. Run
       ```
       xmllint --schema TraitData.xsd  TEST_XML_DATA --noout
       ```
    where `TEST_XML_DATA` is the name of your data file.

See the next comment for more about the syntax and semantics of the data file, and how the app uses it.

**Comment by gsrohde** [comment]
#### Schema of the XML data files

An extensive description of the required format of a trait data XML file is contained in an annotation at the top of the schema document here: https://github.com/PecanProject/bety/blob/draft_insertion_api/api_stuff/TraitData.xsd

A barebones sample file—the simplest possible—is here: https://github.com/PecanProject/bety/blob/draft_insertion_api/api_stuff/SIMPLE_XML_TEST_DATA

See the next comment for information about error handling.

**Comment by gsrohde** [comment]
#### Error handling in the insertion API

Errors may occur at various stages:
1. **Validation stage**: The XML is parsed to see that it has the required form.  Due to limitations of W3C XML Schema, some formal errors can't be caught at this stage.  (I'm considering replacing or supplementing W3C XML Schema for this reason.)  The reason for using an XML schema is so that errors are caught early.  It is also easier to program the API if certain assumptions can be made about the form of the input.
2. **Lookup stage**: Every trait _must_ be associated with a variable, and so we must look up the description of the variable given in the XML file to see that a unique match exists.  Traits _may_ be associated with other entities (e.g., sites, species, citations), so lookups occur for these as well if they are specified in the data file.  Anytime a look-up fails, the XML document is annotated with an error attribute on the element that couldn't be uniquely matched.  (The XML document will later be converted to JSON and returned to the user in the HTTP response.)
3. **Rails validation stage**: Models in Rails may have certain validity constraints.  If one or more of these constraints is violated in the process of attempting to create a model instance, the resulting error messages are collected and sent back in the HTTP response, both in a `model_validation_errors` list and in an annotation to the offending `trait` node in the XML document.
4. **SQL validation stage**: Not all database constraints are captured in the Rails models, so it is possible insertion into a database table will fail due to a constraint violation (or possibly some other reason).  Again, messages from these errors are captured and returned in the response.

Note that the database insertions are run inside a transaction.  This means if one insertion fails, the whole upload is rolled back.

**Comment by gsrohde** [comment]
#### Remaining issues and to-do list
1. No authentication or authorization is in place.  Should we use the `users` table, and if so, should we authenticate with username and password, with API keys, or both (either)?  Should authentication credentials be passed in the data, where they are less likely to get stored (e.g.) in the server logs?
2. Error output is fairly complete, but there is probably some room for improvement.  Is a JSON response OK, or should we return responses in the same form (XML) as the request data?
3. Since the main use case for this will probably be data from sensors, I assumed input would always have complete date-time information (i.e., at least to the nearest second) and so always use a dateloc value of 5 (accurate to the day) and timeloc value of 1 (accurate to the second) whenever a date is given.    (If no date is given, both values are set to 9 (no data).)  Do we want to allow other values?
4. The validation step uses W3C XML Schema, but this has a somewhat steeper learning curve than other XML schema languages.  A schema in RelaxNG, for example, would probably be somewhat comprehensible even to someone having no familiarity with the language.  (I used W3C XML Schema because I am more familiar with it myself.)  Also, RelaxNG, Schematron, and XSLT allow some sorts of constraints that aren't possible using W3C XML Schema alone.  Since the main use case may involve XML files of a fairly regular form, however, this may not be much of an issue.
5. XML with W3C XML Schema is a great way (for me at least) to think through the issues involved in uploading data.  But how well will it scale?  Would JSON be faster?  Can we get robust validity checking if we use JSON?
6. I only grudgingly support allowing the specification of associations (site, citation, species, cultivar, for example) by their id numbers.  (The bulk upload feature _doesn't_ allow this.)  I would like to turn this support off.
7. The BETYdb database uses datatype NUMERIC(16,4) for `traits.mean`, `yields.mean`, `covariates.level`, and `managements.level` and also for `traits.stat`, `yields.stat`, and `covariates.stat`.  It seems to me these should all be floating-point types.  (Perhaps @doracai can weigh in on this.)  According the PostgreSQL documentation, numeric calculation with floating-point types is faster than with arbitrary precision ("numeric") types.  Moreover, by limiting values to four decimal digits, values less than 0.01 can only have two significant digits.  Large values can have 16, which is more than we would ever need.  (Some existing values have as many as 7 s.d., which is almost certainly more than is warranted.  These may have arisen from unit conversions during data entry.)  Now would be a good time to convert these if we wish to do so.  Along these lines, do we want to limit the number of significant digits in uploaded data either by limiting the number of significant digits for values in the data file or by rounding those values before database insertion?
8. I think it may make sense to refactor the Bulk Upload code to use much of the code written for this API.  CSV files can be converted to XML, and then processing from there on can be done uniformly.
9. No automated testing has been written for the API code.
10. Do we want more stringent requirements on upload data?  For example, I don't require a site or a species or a citation to be associated with a trait because neither the database itself nor the Rails app validation constraints requires them.  Should we?
11. Some code cleanup will undoubtably be necessary.  For example, `/api_stuff` is probably not the best location for the schema files.
12. I haven't yet dealt with HTTP status codes.

**Comment by dlebauer** [comment]
Scott, this looks like a great start, though I would like @max-zilla, @robkooper, and @doracai to also weigh in.

I was wrong about having wanting to have the API accept .csv files - this was related to my incorrect understanding of data, but @robkooper patiently explained to me why converting tables to key:value pairs is useful.  To import and return tables, we can either write client-side importers as needed or provide a special case API endpoint.


A few thought and questions : 

  * I notice that your schema has both key:value pairs and complex data types with attributes ( [xml](https://github.com/PecanProject/bety/blob/draft_insertion_api/api_stuff/SIMPLE_XML_TEST_DATA) and / [xsd](https://github.com/PecanProject/bety/blob/draft_insertion_api/api_stuff/TraitData.xsd)). Will this make converting to json harder? Can you use xsd with json? 
  * Rob suggested keeping the GET and PUT requests consistent, i.e. json.
  * or are there benefits to using attributes?
* Eventually we will need to import and export data and provide in [ICASA](http://research.agmip.org/display/dev/JSON+Data+Objects#JSONDataObjects-Sampleobserveddataobject) and [BRAPI](http://docs.brapi.apiary.io/) formats. Can we do anything at this point to either adopt their existing schemas and / or make it easier to create converters that read and write them? Do we need to start from scratch here?

**Comment by gsrohde** [comment]
@dlebauer Regarding your first (and third) bullet points, I generally used attributes for all data values, which are either numbers or short snippets of text.  The exception is the `trait/notes` element, which is the only _element_ having type `string`.  This is because I wanted to allow free-form text.  (I should probably use an element rather than an attribute for the entity notes column as well.)  Most other text values are either candidate keys or parts of candidate keys.  All the other elements only have attributes and/or child elements.  As for using XSD with JSON, you can't.  But I'm fairly sure there are schema languages for JSON.  I'm just not familiar with them.

Regarding ICASA and BRAPI formats, it was hard for me to tell how exactly they relate to the data we have—they seem to have to do with a lot of types of information that we don't collect.  But I only took a quick look, so I can't really answer your question at this point.

**Comment by dlebauer** [comment]
Here are some examples of ICASA data

**Comment by max-zilla** [comment]
I'm taking some time this week to look over the draft_insertion_apis branch at the work @gsrohde has done. 

Yesterday @doracai stopped by my office and we discussed how, eventually, she intends to query BETYdb based on a set of images that are returned in a Clowder query. In order for this to be possible Clowder must provide whatever unique identifiers necessary to get the relevant data from BETY - these IDs (barcodes+species+genotype mentioned in #36?) will likely be populated by Danforth/MAC before sending the data, or by an extractor within Clowder. Basically, we'll need to coordinate either end of this process so that we can get the data we need, and so we don't end up duplicating code.

**Comment by gsrohde** [comment]
@max-zilla As noted above, I temporarily moved http://pecandev.igb.illinois.edu/beta off the draft_insertion_api branch.  If this is inhibiting your work in any way, let me know and I'll set it back up.

**Comment by gsrohde** [comment]
@max-zilla I've restored this.  I've also added some rudimentary authentication, so you now need to use the `-u` option to curl.  I've modified the "Testing out the API" notes above accordingly.

**Comment by gsrohde** [comment]
@max-zilla et al.: I've added a JSON-based API for inserting data analogous to the XML API, and I've added a sample file which can be used to test it out.  Here's the call:
```
curl -u carya:illinois -X POST --data-binary @TEST_JSON_DATA pecandev.igb.illinois.edu/beta/api/v0/traits.json
```
This assumes you have a copy of the file `TEST_JSON_DATA` in the working directory.

I still need to implement better error handling, and I need to document the JSON format.  But if you understand the XML formatting requirements, you can probably figure out the JSON format—they are entirely analogous.

**Comment by gsrohde** [comment]
@dlebauer , @robkooper , @doracai (and @max-zilla): I've put some sample queries using recent extensions to the query API into bety issue https://github.com/PecanProject/bety/issues/381.  You might want to at least take a look before the meeting tomorrow.

**Comment by dlebauer** [comment]
@gsrohde please close, create new issue for documentation if necessary

**Comment by gsrohde** [comment]
Closing.  Any remaining tasks are now in issue #124.
