### ISSUE TITLE
canopy cover GAN

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#526]
@ZongyangLi can you point me to any code or create a PR for this? It was mentioned at Danforth meeting as something Zhenbin needs. Thanks.

**Comment by ZongyangLi** [comment]
GAN is a color correction method to enhance rgb image, base on GPU service.

I think what @zhenbinHU needs is canopy cover percentage estimation value, which was already created by our pipeline.

Since this is GPU based, my plan is:

- first add @Paheding 's quality score code into existed canopy cover extractor
- then add plant mask output from this extractor(or implement another separated extractor for plant mask?)
- at last we finalize GAN when we have GPU sources.

**Comment by ZongyangLi** [comment]
Here is the code for GAN:
https://github.com/terraref/extractors-stereo-rgb/tree/rgb-mask-%26-GAN-enhancement/canopy-cover-enhancement

**Comment by max-zilla** [comment]
This issue is superseded by:
https://github.com/terraref/computing-pipeline/issues/532
