### ISSUE TITLE
Point utilities to terraref.ncsa.illinois.edu/*

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#56]
Currently we are hosting two instances of BETYdb on pecandev.igb.illinois.edu. @robkooper is setting them up on the Nebula instance of OpenStack (#24, #65). Once he reports the ip addresses, We can point the production instances of Clowder and Bety to these URLs:

  * http://terraref.ncsa.illinois.edu/clowder
  * http://terraref.ncsa.illinois.edu/bety
  * http://terraref.ncsa.illinois.edu/bety-test

**Comment by rachelshekar** [comment]
help+neteng
host at NCSA instead of Github (nebula as vm?)
Talk to Bill Glick about redirects

**Comment by dlebauer** [comment]
@robkooper thank you for getting the redirects working, but the redirects fail for API calls, e.g. using terraref.ncsa.illinois.edu/betydb/search?genus=Miscanthus should work but it just redirects to the pecandev url.

@gsrohde it is not clear from the online docs (betydb.org/api/docs) how to construct an API call from the current api docs. e.g. shouldn't https://www.betydb.org/api/beta/citations:50 work?

**Comment by gsrohde** [comment]
It’s https://www.betydb.org/api/beta/citations/50<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.betydb.org_api_beta_citations-3A50&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=oJsSpSeia9tFOpzHxC6EpYUew62qA42qdvjRrEjQywI&m=kzu7Ez0X3KC9Qd3OqSj6iLTBDSWaD1Ey5390aMMSZXA&s=7_0tH66B77bXvraSCM1Ruh4zenIEZ5umbl5Xd-Z3ML8&e=>, and you have to add a query string with key=<your api key>.  I’ve thought about removing the requirement for a key so that you could easily view the result in a browser once logged in; or, if using curl, you could use the `-u username:password` option instead of a key.  Though, actually, if you are logged in, even a bad key (or just `?key=`) will work.

Regarding the API docs, it does refer to the path `GET /api/beta/citations/:id<http://bety-dev:3000/api/docs/beta/citations/show.html>`, so it should be clear that you need a forward slash after `citations`.  What’s not clear, perhaps because this automatically-generated documentation is too “Rails-developer-centric”, is that the placeholder of the id parameters is called “:id”, so that when you replace this with a number, you should be replacing the colon as well.

**Comment by max-zilla** [comment]
Can this be closed now?

**Comment by dlebauer** [comment]
@max-zilla no, please do not close. Two urls for the BETYdb instances do redirect to pecandev.igb.illinois.edu, but we still need to

1. migrate BETYdb from pecandev.igb.illinois.edu to OpenStack on Nebula or Roger 
2. have daily backups of both instances
3. the API endpoints on both http://terraref.ncsa.illinois.edu/bety and
http://terraref.ncsa.illinois.edu/bety-test need to function

**Comment by dlebauer** [comment]
bety --> bety6 -->  https://terraref.ncsa.illinois.edu/bety --> http://141.142.209.94/bety
bety-test --> bety7 -->  https://terraref.ncsa.illinois.edu/bety-test --> http://141.142.209.95/bety-test

**Comment by dlebauer** [comment]
closing this: remaining issues of backups are addressed in #65
