### ISSUE TITLE
Globus transfer status checker 

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#62]
Write a script that will periodically check Globus to determine if transfer has finished successfully.

daemon listens to directory 

This is required because Globus doesn't currently do this.

This will run next to Clowder.

**Comment by dlebauer** [comment]
@robkooper (or reassign) please flush out specifications of this feature, making sure it is clear what is required and what would be nice to have (I am naiive but what other than a cron job to check for newly finished transfers every X min would is necessary? nice to have?).

**Comment by robkooper** [comment]
Here is the pseudo code for the program:

/upload : expects following data to be passed in, will only accept request if globus username is known. Once it accepts it, add to a local queue that is checked all the time (and saved to disk).
```
[ {
  user: "globus username",
  globus_id: "globus id of upload",
  files: [ "file1", "file2", ... ],
}]
```

/upload/:id checks to see if the globus id is finished (i.e. is no longer in the list of uploads in progress), if in upload.list return "IN PROGRESS", otherwise check done list and return error code.

main loop
```
while(true) {
  for(entry in upload.list) {
    switch check upload as user in entry {
      case DONE : tell clowder upload is finished; remove from upload.list; add to done list
      case ERROR: mark as error in log file; remove from upload list; add to done list
    }
  }
}
```

This upload/done list can be kept in mongo/postgresql/file.

**Comment by max-zilla** [comment]
Assigning this to myself because I'm working on it now.

Not currently sure where the components of this will go (standalone service? hooks to some Clowder plugin? etc.) but I've created a Clowder branch for now:
https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/browse?at=refs%2Fheads%2Fglobus-status-checker

**Comment by robkooper** [comment]
Should be standalone i think. We can put this in the scripts folder here in computing-pipeline. It will use the clowder api, but that is it.

**Comment by dlebauer** [comment]
Standalone if possible - except where it is onerous or interferes with the scientific goals of the project, we should keep pipeline components modular and reusable.

**Comment by max-zilla** [comment]
Roger that. Moved the code to a branch of computing-pipeline and deleted the clowder branch.

https://github.com/terraref/computing-pipeline/tree/globus-monitor-api

**Comment by dlebauer** [comment]
@max-zilla what remains to be done on this issue? What happens when it fails?

**Comment by max-zilla** [comment]
This discussion has largely moved to #79. The basics of what is described here are implemented and committed in this branch:
https://github.com/terraref/computing-pipeline/tree/globus-monitor-api/scripts (globusmonitor/gantrymonitor)
