### ISSUE TITLE
Deploy BETYdb API to TERRA instances

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#78]
Scott just committed the v0 API to the BETYdb master  branch https://github.com/PecanProject/bety/commit/494767e03af17dc33eb590eba3367da90af34823

Please:

* Create a new release
* deploy these to the existing TERRA instances of BETYdb (mepp, terra-test, and terra-ref)

@robkooper when will the test and references instances be migrated to their more permanent location (#65)?

**Comment by dlebauer** [comment]
@gsrohde it is not clear from the online docs (betydb.org/api/docs) how to construct an API call from the current api docs. e.g. shouldn't https://www.betydb.org/api/beta/citations:50 work?

**Comment by gsrohde** [comment]
@dlebauer It’s https://www.betydb.org/api/beta/citations/50, and you have to add a query string that includes `key=<your api key>`.  I’ve thought about removing the requirement for a key so that you could easily view the result in a browser once logged in; or, if using curl, you could use the `-u username:password` option instead of a key.  Though, actually, if you are logged in, even a bad key (or just `?key=`) will work.

Regarding the API docs, it does refer to the path `GET /api/beta/citations/:id`, so it should be clear that you need a forward slash after `citations`.  What’s not clear, perhaps because this automatically-generated documentation is too “Rails-developer-centric”, is that the placeholder of the id parameters is called “:id”, so that when you replace this with a number, you should be replacing the colon as well.

**Comment by dlebauer** [comment]
> What’s not clear, perhaps because this automatically-generated documentation is too “Rails-developer-centric”

This is where examples come in. I can't recall - does apipie and / or the testing suite provide a framework for this?

The other bit that is not clear to me is how to chain parameters together multiple parameters.
