### ISSUE TITLE
Integrate secondary MAC Irrigation and met data streams 

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#80]
Pedro is setting up two new data streams: 
### Irrigation data:

basestation with web interface. I think http://www.baselinesystems.com/products.php/basemanager-central-control (please confirm with Pedro)

Data types: 
- Flow rate 
- Pressure 
- Irrigation performance 
- Soil moisture 
### Weather station

Independent from Lemnatec data stream. Will be captured in field by Campbell data logger
## TODO
- Pedro: send specifications to JD
- JD: contact Pedro to determine how to merge these streams w/ Lemnatec data
- This data stream and the one from the lemnatec scanner (terraref/reference-data#26) will be converted to a common weather data product following documentation here: https://github.com/terraref/documentation/blob/master/environmental_data.md
- add to geostreams

**Comment by jdmaloney** [comment]
Weather station is getting close to completion.  NAS for central data dumping should be on its way to MAC.  Tests on an identical unit have been successful, just waiting for the real thing to be in place and gathering data.

**Comment by jdmaloney** [comment]
New NAS in place, waiting for data to start dumping it so I can build my script to grab it.

**Comment by rachelshekar** [comment]
@jdmaloney please update

**Comment by jdmaloney** [comment]
Data arrives weekly or monthly, dumping it to gantry-cache, working with Max on log format and naming before full automation

**Comment by jdmaloney** [comment]
Full automation of Weather and Lightning data complete, working with Pedro to get a better solution than email for irrigation

**Comment by dlebauer** [comment]
At a minimum could he upload files directly to Clowder?

**Comment by jdmaloney** [comment]
I'm getting ready to email him, I'm going to try and get it so he just transfers it to a folder on the same NAS where we get weather/lightning data, and my same code can grab it from there.  That way there's nothing new to write and we get the files on the ROGER file system so we can see them apart from Clowder and they'll get backed up with normal backup procedures.

**Comment by jdmaloney** [comment]
Irrigation directory on NAS created, script is also now watching that folder.  Waiting for files to get dropped in, once a test one completes then we're good

**Comment by jdmaloney** [comment]
Done

**Comment by dlebauer** [comment]
JD could you please create another issue that states where / what these
streams are and adds the new streams to the environmental logger extractor?

**Comment by jdmaloney** [comment]
@dlebauer A bit confused on what you mean.  I can open another issue and put the paths for the data on the ROGER side in it, and give a description (based on what little I know about the data). Is the issue going to be for whoever writes the extractor for that data?  If so who should I assign it to? (or just leave it unassigned)

**Comment by dlebauer** [comment]
That is correct, the new issue would be to add the transferred data to the
environmental logger. You can assign it to me for now.

**Comment by dlebauer** [comment]
@jdmaloney I am not sure why this one was closed. Where are the irrigation data going? Are they being processed by the weather data extractor?

**Comment by jdmaloney** [comment]
Irrigation data is dropped on the NAS by Pedro manually, supposedly monthly if I remember the plan correctly.  It hasn't been put on the NAS since we had the code in place to grab it (which has been checking since August). He places it there manually as he has to download it by hand from their special website thing, I'll ping him in email here to have him download it all and put it in there.  I think they come as .csv files?  The script is checking the NAS, and would copy the files over, and notify Max's code to pick them up and move them to ROGER.  They'd end up in /gpfs/largeblockFS/projects/arpae/terraref/sites/ua-mac/raw_data/irrigation/yyyy-mm-dd/XXX.csv.  As for extractors, I don't know, though I'd venture to guess no, since there are no data products for them to work with at this time.  

I'll follow up in this issue once we have a successful file drop from Pedro.   Once that happens, I'll actually do what I had said above and open an new issue and assign it to a programmer (maybe @max-zilla  to start with, and he can delegate it) for the purpose of tracking the new extractor development/modification to a current extractor.  Then close this issue again.

**Comment by jdmaloney** [comment]
Oh, just found out Pedro has an account here in the GitHub.

@Andrade-Pedro Could you dump the irrigation data onto the NAS (as far back as you have it)?  I'll suck it in and make sure it lands on the ROGER system here at NCSA.

**Comment by Andrade-Pedro** [comment]
@jdmaloney I Just dropped 12 files on NAS server, one per month starting from March 2016

**Comment by rachelshekar** [comment]
@jdmaloney - please give an update

**Comment by jdmaloney** [comment]
This was completed and integrated into the transfer pipeline.

**Comment by dlebauer** [comment]
@jdmaloney The final step was to add this data to the geostreams database ... not sure if this has been done, so I am re-opening. @harshagrawal28 did you finish adding the irrigation data? Can you point to it?

**Comment by max-zilla** [comment]
@dlebauer yes, this was done several weeks ago.

https://terraref.ncsa.illinois.edu/clowder/api/geostreams/datapoints?stream_id=750

(you'll need to add &key=SECRETKEY to get results right now, i need to finish making those endpoints public)
