### ISSUE TITLE
data capture logs

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#92]
To meet the milestone of 'successful data capture', we need to 

* confirm that gantry is collecting all expected data streams
* all of the data being generated by field gantry is making it to roger and made available in Clowder

We need to record:

* what data was transferred, from what sensors, per day
* did all files generated by gantry make it to Roger? 
* did all datasets get captured by Clowder?
* what checks have been passed
  * md5sum
  * one metadata per dataset
  * does each metadata file have valid and minimum required information
* summary of files (mean, count, sd by time point)

(anything else?)

We need to provide this information as a text file and perhaps html report. 

Given a text log file, I could write an R markdown script to parse it and generate tables in html format.

**Comment by robkooper** [comment]
As a FYI clowder will compute a SHA-512 for every file that you can get.

**Comment by jdmaloney** [comment]
@dlebauer @robkooper  Is a good chunk of this something that should be implemented in Max's code?

**Comment by dlebauer** [comment]
>  that should be implemented in Max's code?

that seems reasonable, as long as we have a fall back or three if the code stops running ...

**Comment by max-zilla** [comment]
ok so...

what data was transferred, from what sensors, per day
- this is captured in several places (FTP log, gantry monitor log, ROGER completed logs) - however there's no step on Roger side to aggregate these into a report. Needs to be implemented.

did all files generated by gantry make it to Roger?
- When files arrive on Roger, message is sent back to gantry to create a symlink in /delete folder for removal from gantry. files that remain on gantry from more than a few days ago were likely missed. Aside from verifying the logs and checking for leftover files, this should be implicit in the logging steps. 

did all datasets get captured by Clowder?
- in the log an entry is made every time a dataset is created. we could parse these logs to create an extracted list of datasets and compare to the file/folder structure.

what checks have been passed
- md5sum - this is done once by Globus upon arrival on Roger, and can potentially be done again by Clowder after file upload.

- one metadata per dataset - because metadata and files can arrive asynchronously, this should be treated like a file - if we got a metadata.json file, did it end up in the right place?

- does each metadata file have valid and minimum required information - this one is more nebulous

summary of files (mean, count, sd by time point) - we should flesh this out a bit more.

**Comment by max-zilla** [comment]
Just updated my comment after discussions with @jdmaloney

**Comment by max-zilla** [comment]
Assuming no new issues arise with the pipeline, improving these logs will be one of my main focuses for next week in anticipation of end of May milestone.

**Comment by max-zilla** [comment]
We are now capturing all necessary information listed in this issue:
- gantry -> Roger transfers
- Roger -> Clowder updates
- files and metadata uploads are tracked

..with the exception of verifying sanity ranges in the metadata fields. I will create a followup issue for refining logs by using something like LogStash to create reports/digests to make them more readable.
https://github.com/terraref/computing-pipeline/issues/106
